FROM clojure:temurin-8-lein-jammy
LABEL maintainer=frederic.merizen@soft-xki.com
LABEL maintainer=jon@jaggersoft.com

ENV LEIN_ROOT=1
COPY project.clj /tmp

COPY install.sh .
RUN ./install.sh && rm -f ./install.sh
